/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#a6c8ff",
        "secondary": "#005fb0",
        "surface-container": "#ebeef3",
        "tertiary": "#002b12",
        "primary-container": "#1f3a60",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d5e3ff",
        "on-error": "#ffffff",
        "accent-success": "#10B981",
        "on-primary-fixed-variant": "#2d476e",
        "on-background": "#181c20",
        "surface-bright": "#f7f9ff",
        "surface": "#f7f9ff",
        "surface-container-low": "#f1f4f9",
        "primary-fixed": "#d5e3ff",
        "outline": "#74777f",
        "inverse-surface": "#2d3135",
        "on-tertiary-container": "#56b674",
        "on-secondary-container": "#003a6f",
        "background": "#f7f9ff",
        "on-tertiary-fixed-variant": "#005228",
        "background-main": "#F4F7FA",
        "surface-dim": "#d7dadf",
        "primary": "#032449",
        "primary-fixed-dim": "#aec8f5",
        "outline-variant": "#c4c6cf",
        "tertiary-container": "#00431f",
        "secondary-container": "#63a5fd",
        "surface-white": "#FFFFFF",
        "inverse-primary": "#aec8f5",
        "on-secondary-fixed-variant": "#004786",
        "surface-variant": "#e0e3e8",
        "error": "#ba1a1a",
        "action-blue": "#3B82F6",
        "surface-tint": "#465f87",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e0e3e8",
        "on-primary-fixed": "#001b3c",
        "surface-container-high": "#e5e8ee",
        "on-secondary-fixed": "#001c3b",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#7ada95",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef1f6",
        "tertiary-fixed": "#96f7af",
        "on-primary-container": "#8ba4d1",
        "on-tertiary-fixed": "#00210c",
        "on-surface-variant": "#43474e",
        "deep-navy": "#0B1320"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-md": "1rem",
        "gutter": "1.5rem",
        "stack-lg": "2rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2rem",
        "stack-sm": "0.5rem"
      },
      fontFamily: {
        "headline-h1-mobile": ["Inter", "sans-serif"],
        "headline-h3": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-h2": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "headline-h2-mobile": ["Inter", "sans-serif"],
        "headline-h1": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-h1-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-h3": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-h2": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "button": ["14px", { "lineHeight": "1", "fontWeight": "600" }],
        "headline-h2-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
